[package]
name = "t8bar"
version = "0.1.0"
authors = ["Eduardo Cunha <hey@drgmr.com>"]
edition = "2018"

[dependencies]
log = "0.4.7"
env_logger = "0.6.2"
serde = "1.0.97"
serde_json = "1.0.40"
serde_derive = "1.0.97"
fruitbasket = "0.8.0"
rubrail = "0.9.0"
reqwest = "0.9.19"
